server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?serverTimezone=UTC&Unicode=true&characterEncoding=UTF-8
    username: root